In [202]:
df_cluster_1 = pd.read_csv('cluster_1.csv')
df_cluster_4 = pd.read_csv('cluster_4.csv')
df_cluster_5 = pd.read_csv('cluster_5.csv')

In [203]:
df_cluster_1.head()

,CARDNUM,PROD1,PROD2,PROD3,PROD4,PROD5,PROD6,PROD7,PROD8,PROD9,...,PROD51,PROD52,PROD53,PROD54,PROD55,PROD56,PROD57,PROD58,PROD59,cluster
0,3,1504:\nCHEESE,2201:\nSAYUR TAN,1003: FRUIT\nJUI,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1
1,6,1424:\nCHOCOLATE,1008:\nWATER,1500: FRESH\nMIL,1453:\nINSTANT D,1421:\nSOFT\nCAND,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1
2,2,1222: Sanitary,1502: DAIRY\nDES,1414: ROLLS,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1
3,5,1440: BABY\nMILK,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1
4,10,1440: BABY\nMILK,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1

In [204]:
df_cluster_4.head()

,CARDNUM,PROD1,PROD2,PROD3,PROD4,PROD5,PROD6,PROD7,PROD8,PROD9,...,PROD51,PROD52,PROD53,PROD54,PROD55,PROD56,PROD57,PROD58,PROD59,cluster
0,4,1440: BABY\nMILK,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4
1,4,1441: BABY\nFOOD,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4
2,4,1110: Laundry\nd,1220: Tissue,1105:\nDeodorisa,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4
3,4,2301: TOAST\nBRE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4
4,4,2001: Main\nDish,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4

In [205]:
df_cluster_5.head()

,CARDNUM,PROD1,PROD2,PROD3,PROD4,PROD5,PROD6,PROD7,PROD8,PROD9,...,PROD51,PROD52,PROD53,PROD54,PROD55,PROD56,PROD57,PROD58,PROD59,cluster
0,1,1440: BABY\nMILK,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5
1,1,1440: BABY\nMILK,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5
2,1,1216: Baby\nHygi,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5
3,1,2201: SAYUR\nTAN,1403:\nMODERN SN,1451:\nNOODLES &,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5
4,1,1001: NON\nCARBO,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5

In [206]:
print(df_cluster_1.shape)
print(df_cluster_4.shape)
print(df_cluster_5.shape)

(78, 61)
(9, 61)
(13, 61)

In [207]:
df_cluster_1 = df_cluster_1.drop(['CARDNUM', 'cluster'], axis=1)
df_cluster_4 = df_cluster_4.drop(['CARDNUM', 'cluster'], axis=1)
df_cluster_5 = df_cluster_5.drop(['CARDNUM', 'cluster'], axis=1)

In [208]:
print(df_cluster_1.shape)
print(df_cluster_4.shape)
print(df_cluster_5.shape)

(78, 59)
(9, 59)
(13, 59)

In [209]:
df_cluster_1.head()

,PROD1,PROD2,PROD3,PROD4,PROD5,PROD6,PROD7,PROD8,PROD9,PROD10,...,PROD50,PROD51,PROD52,PROD53,PROD54,PROD55,PROD56,PROD57,PROD58,PROD59
0,1504:\nCHEESE,2201:\nSAYUR TAN,1003: FRUIT\nJUI,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1424:\nCHOCOLATE,1008:\nWATER,1500: FRESH\nMIL,1453:\nINSTANT D,1421:\nSOFT\nCAND,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1222: Sanitary,1502: DAIRY\nDES,1414: ROLLS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,1440: BABY\nMILK,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,1440: BABY\nMILK,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [210]:
df_cluster_4.head()

,PROD1,PROD2,PROD3,PROD4,PROD5,PROD6,PROD7,PROD8,PROD9,PROD10,...,PROD50,PROD51,PROD52,PROD53,PROD54,PROD55,PROD56,PROD57,PROD58,PROD59
0,1440: BABY\nMILK,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1441: BABY\nFOOD,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1110: Laundry\nd,1220: Tissue,1105:\nDeodorisa,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2301: TOAST\nBRE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2001: Main\nDish,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [211]:
df_cluster_5.head()

,PROD1,PROD2,PROD3,PROD4,PROD5,PROD6,PROD7,PROD8,PROD9,PROD10,...,PROD50,PROD51,PROD52,PROD53,PROD54,PROD55,PROD56,PROD57,PROD58,PROD59
0,1440: BABY\nMILK,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1440: BABY\nMILK,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1216: Baby\nHygi,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2201: SAYUR\nTAN,1403:\nMODERN SN,1451:\nNOODLES &,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,1001: NON\nCARBO,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [215]:
# convert pandas dataframe to list and then to one hot encoding
# cluster 1
records = []
for i in range(0, df_cluster_1.shape[0]):
    records.append([str(df_cluster_1.values[i,j]) for j in range(0, df_cluster_1.shape[1])])
    
te = TransactionEncoder()
te_ary = te.fit(records).transform(records)
df_cluster_1_transform = pd.DataFrame(te_ary, columns=te.columns_)
df_cluster_1_transform.drop(['nan'], axis=1, inplace=True)
df_cluster_1_transform

,1001: NON CARBO,1003: FRUIT JUI,1004: FRUIT JUI,1008: WATER,1103: BATHROOM,1105: Deodorisa,1106: Insectici,1110: Laundry d,1111: Laundry C,1201: FACE CARE,...,469: MENS CASUA,520: MASSTIGE C,523: FRAGRANCE:,6111: Ladies So,6231: Zelia Top,6302: Toys For,BA04: BATTERY C,BL01: MULTI PUR,CA20: STATIONER,CA88: HEALTH AN
0,False,True,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,False,False,False,True,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
5,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
6,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
7,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
8,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
9,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
10,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
11,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
12,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
13,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
14,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
15,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
16,False,False,False,False,False,True,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
17,False,False,False,False,False,True,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
18,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
19,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
20,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
21,False,False,False,False,True,False,False,True,False,False,...,False,False,False,False,False,False,False,False,False,False
22,False,False,False,False,False,False,False,False,False,True,...,False,False,False,False,False,False,False,False,False,False
23,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
24,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
25,True,False,True,False,False,False,False,False,True,False,...,False,False,False,False,False,False,False,False,False,False
26,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,True,False,False
27,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
28,False,False,False,False,False,False,False,False,False,False,...,False,True,False,False,False,False,False,False,False,False
29,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
48,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
49,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
50,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
51,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
52,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
53,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
54,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
55,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
56,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
57,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
58,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
59,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
60,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
61,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
62,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
63,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
64,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,True,False,False,False,False,False
65,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
66,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
67,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
68,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
69,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
70,False,False,False,False,False,False,False,False,False,False,...,False,False,True,False,False,False,False,False,False,False
71,False,False,False,False,False,False,False,False,False,False,...,True,False,False,False,False,False,False,False,False,False
72,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,True,False,False,False,False
73,False,False,False,False,False,False,False,False,False,False,...,True,False,False,False,False,False,False,False,False,False
74,False,False,False,False,False,False,False,False,False,False,...,False,False,False,True,False,False,False,False,False,False
75,False,False,False,False,False,False,False,False,False,False,...,False,True,False,False,False,False,False,False,False,False
76,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
77,False,False,False,False,False,True,True,False,False,False,...,False,False,False,False,False,False,False,False,False,False

In [216]:
# convert pandas dataframe to list and then to one hot encoding
# cluster 4
records = []
for i in range(0, df_cluster_4.shape[0]):
    records.append([str(df_cluster_4.values[i,j]) for j in range(0, df_cluster_4.shape[1])])
    
te = TransactionEncoder()
te_ary = te.fit(records).transform(records)
df_cluster_4_transform = pd.DataFrame(te_ary, columns=te.columns_)
df_cluster_4_transform.drop(['nan'], axis=1, inplace=True)
df_cluster_4_transform

,1105: Deodorisa,1110: Laundry d,1210: SOAP,1220: Tissue,1440: BABY MILK,1441: BABY FOOD,2001: Main Dish,2301: TOAST BRE,4140: Hair Care,462: LADIES CAS,6211: LT GIRL T
0,False,False,False,False,True,False,False,False,False,False,False
1,False,False,False,False,False,True,False,False,False,False,False
2,True,True,False,True,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,True,False,False,False
4,False,False,False,False,False,False,True,False,False,False,False
5,False,False,False,False,False,False,False,False,True,False,False
6,False,False,True,False,False,False,False,False,False,False,False
7,False,False,False,False,False,False,False,False,False,True,False
8,False,False,False,False,False,False,False,False,False,False,True

In [217]:
# convert pandas dataframe to list and then to one hot encoding
# cluster 5
records = []
for i in range(0, df_cluster_5.shape[0]):
    records.append([str(df_cluster_5.values[i,j]) for j in range(0, df_cluster_5.shape[1])])
    
te = TransactionEncoder()
te_ary = te.fit(records).transform(records)
df_cluster_5_transform = pd.DataFrame(te_ary, columns=te.columns_)
df_cluster_5_transform.drop(['nan'], axis=1, inplace=True)
df_cluster_5_transform

,1001: NON CARBO,1105: Deodorisa,1216: Baby Hygi,1403: MODERN SN,1436: SPREAD,1440: BABY MILK,1451: NOODLES &,1462: SALT & SP,1500: FRESH MIL,1540: TOAST BRE,2201: SAYUR TAN,2310: SWEET BUN,4100: Iron,454: MEN CASUAL,520: MASSTIGE C,BI10: CHILDREN',CA88: HEALTH AN
0,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False
2,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,True,False,False,True,False,False,False,True,False,False,False,False,False,False
4,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
5,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True
6,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False
7,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False
8,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False
9,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False
10,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False
11,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False
12,False,True,False,True,True,False,False,True,True,True,False,False,False,False,False,False,False

In [52]:
# Build up the frequent items# Build  
frequent_itemsets = apriori(df_transform, min_support=0, use_colnames=True)

In [53]:
frequent_itemsets.shape

(1023, 2)

In [33]:
frequent_itemsets.head()

    support   itemsets
0  0.422111   (Anggur)
1  0.396985    (Jeruk)
2  0.402010  (alpokat)
3  0.437186    (jambu)
4  0.412060    (kurma)

In [54]:
many_bundling = 4
for index, row in frequent_itemsets.iterrows():
    if(len(row['itemsets']) == many_bundling):
        result_bundling = frequent_itemsets.loc[[index]]
        break

result_bundling

      support                         itemsets
175  0.015075  (alpokat, jambu, Jeruk, Anggur)

In [39]:
len(bundling)

120

In [43]:
frequent_itemsets.loc[[174]]

      support             itemsets
174  0.030151  (pisang, pir, sawo)

In [44]:
frequent_itemsets.loc[[55]]

     support                  itemsets
55  0.045226  (alpokat, Jeruk, Anggur)

In [40]:
bundling

[55,
 56,
 57,
 58,
 59,
 60,
 61,
 62,
 63,
 64,
 65,
 66,
 67,
 68,
 69,
 70,
 71,
 72,
 73,
 74,
 75,
 76,
 77,
 78,
 79,
 80,
 81,
 82,
 83,
 84,
 85,
 86,
 87,
 88,
 89,
 90,
 91,
 92,
 93,
 94,
 95,
 96,
 97,
 98,
 99,
 100,
 101,
 102,
 103,
 104,
 105,
 106,
 107,
 108,
 109,
 110,
 111,
 112,
 113,
 114,
 115,
 116,
 117,
 118,
 119,
 120,
 121,
 122,
 123,
 124,
 125,
 126,
 127,
 128,
 129,
 130,
 131,
 132,
 133,
 134,
 135,
 136,
 137,
 138,
 139,
 140,
 141,
 142,
 143,
 144,
 145,
 146,
 147,
 148,
 149,
 150,
 151,
 152,
 153,
 154,
 155,
 156,
 157,
 158,
 159,
 160,
 161,
 162,
 163,
 164,
 165,
 166,
 167,
 168,
 169,
 170,
 171,
 172,
 173,
 174]

In [27]:
frequent_itemsets.to_csv('frequent_itemsets.csv', index=False)

In [28]:
frequent_itemsets

       support                                           itemsets
0     0.422111                                           (Anggur)
1     0.396985                                            (Jeruk)
2     0.402010                                          (alpokat)
3     0.437186                                            (jambu)
4     0.412060                                            (kurma)
5     0.391960                                           (mangga)
6     0.422111                                       (naga merah)
7     0.376884                                              (pir)
8     0.417085                                           (pisang)
9     0.447236                                             (sawo)
10    0.130653                                    (Jeruk, Anggur)
11    0.150754                                  (alpokat, Anggur)
12    0.150754                                    (jambu, Anggur)
13    0.145729                                    (kurma, Anggur)
14    0.150754                                   (mangga, Anggur)
15    0.165829                               (Anggur, naga merah)
16    0.155779                                      (Anggur, pir)
17    0.190955                                   (pisang, Anggur)
18    0.160804                                     (Anggur, sawo)
19    0.150754                                   (Jeruk, alpokat)
20    0.155779                                     (Jeruk, jambu)
21    0.165829                                     (kurma, Jeruk)
22    0.135678                                    (mangga, Jeruk)
23    0.150754                                (Jeruk, naga merah)
24    0.125628                                       (Jeruk, pir)
25    0.130653                                    (pisang, Jeruk)
26    0.155779                                      (Jeruk, sawo)
27    0.170854                                   (jambu, alpokat)
28    0.155779                                   (kurma, alpokat)
29    0.125628                                  (mangga, alpokat)
...        ...                                                ...
993   0.000000  (jambu, naga merah, pir, sawo, mangga, pisang,...
994   0.000000  (kurma, naga merah, pir, sawo, mangga, pisang,...
995   0.000000  (kurma, alpokat, jambu, naga merah, pir, mangg...
996   0.000000  (kurma, alpokat, jambu, naga merah, pir, sawo,...
997   0.000000  (kurma, alpokat, jambu, naga merah, sawo, mang...
998   0.000000  (kurma, alpokat, jambu, pir, sawo, mangga, pis...
999   0.000000  (kurma, alpokat, jambu, naga merah, pir, sawo,...
1000  0.000000  (alpokat, jambu, naga merah, pir, sawo, mangga...
1001  0.000000  (kurma, alpokat, naga merah, pir, sawo, mangga...
1002  0.000000  (kurma, jambu, naga merah, pir, sawo, mangga, ...
1003  0.000000  (kurma, jambu, alpokat, naga merah, pir, mangg...
1004  0.000000  (kurma, jambu, alpokat, naga merah, pir, sawo,...
1005  0.000000  (kurma, jambu, alpokat, naga merah, sawo, mang...
1006  0.000000  (kurma, jambu, alpokat, pir, sawo, mangga, pis...
1007  0.000000  (kurma, jambu, alpokat, naga merah, pir, sawo,...
1008  0.000000  (jambu, alpokat, naga merah, pir, sawo, mangga...
1009  0.000000  (kurma, alpokat, naga merah, pir, sawo, mangga...
1010  0.000000  (kurma, jambu, naga merah, pir, sawo, mangga, ...
1011  0.000000  (kurma, jambu, alpokat, naga merah, pir, sawo,...
1012  0.000000  (kurma, alpokat, jambu, naga merah, pir, mangg...
1013  0.000000  (kurma, alpokat, jambu, naga merah, pir, sawo,...
1014  0.000000  (kurma, alpokat, jambu, naga merah, sawo, mang...
1015  0.000000  (kurma, alpokat, jambu, pir, sawo, mangga, pis...
1016  0.000000  (kurma, alpokat, jambu, naga merah, pir, sawo,...
1017  0.000000  (alpokat, jambu, naga merah, pir, sawo, mangga...
1018  0.000000  (kurma, alpokat, naga merah, pir, sawo, mangga...
1019  0.000000  (kurma, jambu, naga merah, pir, sawo, mangga, ...
1020  0.000000  (kurma, alpokat, jambu, naga merah, pir, sawo,...
1021  0.000000  (kurma, jambu, alpokat, naga merah, pir, sawo,...
1022  0.000000  (kurma, alpokat, jambu, naga merah, pir, sawo,...

[1023 rows x 2 columns]

In [24]:
# Create the rules# Create 
rules = association_rules(frequent_itemsets, metric="lift", min_threshold=0)
rules

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,leverage,conviction
0,(Jeruk),(Anggur),0.396985,0.422111,0.130653,0.329114,0.779687,-0.036918,0.861382
1,(Anggur),(Jeruk),0.422111,0.396985,0.130653,0.309524,0.779687,-0.036918,0.873332
2,(alpokat),(Anggur),0.402010,0.422111,0.150754,0.375000,0.888393,-0.018939,0.924623
3,(Anggur),(alpokat),0.422111,0.402010,0.150754,0.357143,0.888393,-0.018939,0.930207
4,(jambu),(Anggur),0.437186,0.422111,0.150754,0.344828,0.816913,-0.033787,0.882042
5,(Anggur),(jambu),0.422111,0.437186,0.150754,0.357143,0.816913,-0.033787,0.875489
6,(kurma),(Anggur),0.412060,0.422111,0.145729,0.353659,0.837834,-0.028206,0.894093
7,(Anggur),(kurma),0.422111,0.412060,0.145729,0.345238,0.837834,-0.028206,0.897944
8,(mangga),(Anggur),0.391960,0.422111,0.150754,0.384615,0.911172,-0.014697,0.939070
9,(Anggur),(mangga),0.422111,0.391960,0.150754,0.357143,0.911172,-0.014697,0.945840
10,(Anggur),(naga merah),0.422111,0.422111,0.165829,0.392857,0.930697,-0.012348,0.951818
11,(naga merah),(Anggur),0.422111,0.422111,0.165829,0.392857,0.930697,-0.012348,0.951818
12,(Anggur),(pir),0.422111,0.376884,0.155779,0.369048,0.979206,-0.003308,0.987579
13,(pir),(Anggur),0.376884,0.422111,0.155779,0.413333,0.979206,-0.003308,0.985039
14,(pisang),(Anggur),0.417085,0.422111,0.190955,0.457831,1.084624,0.014899,1.065885
15,(Anggur),(pisang),0.422111,0.417085,0.190955,0.452381,1.084624,0.014899,1.064453
16,(Anggur),(sawo),0.422111,0.447236,0.160804,0.380952,0.851792,-0.027979,0.892926
17,(sawo),(Anggur),0.447236,0.422111,0.160804,0.359551,0.851792,-0.027979,0.902319
18,(Jeruk),(alpokat),0.396985,0.402010,0.150754,0.379747,0.944620,-0.008838,0.964106
19,(alpokat),(Jeruk),0.402010,0.396985,0.150754,0.375000,0.944620,-0.008838,0.964824
20,(Jeruk),(jambu),0.396985,0.437186,0.155779,0.392405,0.897570,-0.017777,0.926298
21,(jambu),(Jeruk),0.437186,0.396985,0.155779,0.356322,0.897570,-0.017777,0.936827
22,(kurma),(Jeruk),0.412060,0.396985,0.165829,0.402439,1.013739,0.002247,1.009127
23,(Jeruk),(kurma),0.396985,0.412060,0.165829,0.417722,1.013739,0.002247,1.009723
24,(mangga),(Jeruk),0.391960,0.396985,0.135678,0.346154,0.871957,-0.019924,0.922258
25,(Jeruk),(mangga),0.396985,0.391960,0.135678,0.341772,0.871957,-0.019924,0.923753
26,(Jeruk),(naga merah),0.396985,0.422111,0.150754,0.379747,0.899638,-0.016818,0.931699
27,(naga merah),(Jeruk),0.422111,0.396985,0.150754,0.357143,0.899638,-0.016818,0.938023
28,(Jeruk),(pir),0.396985,0.376884,0.125628,0.316456,0.839662,-0.023989,0.911595
29,(pir),(Jeruk),0.376884,0.396985,0.125628,0.333333,0.839662,-0.023989,0.904523
...,...,...,...,...,...,...,...,...,...
58,(jambu),(sawo),0.437186,0.447236,0.170854,0.390805,0.873822,-0.024671,0.907367
59,(sawo),(jambu),0.447236,0.437186,0.170854,0.382022,0.873822,-0.024671,0.910735
60,(mangga),(kurma),0.391960,0.412060,0.130653,0.333333,0.808943,-0.030858,0.881910
61,(kurma),(mangga),0.412060,0.391960,0.130653,0.317073,0.808943,-0.030858,0.890345
62,(kurma),(naga merah),0.412060,0.422111,0.140704,0.341463,0.808943,-0.033231,0.877536
63,(naga merah),(kurma),0.422111,0.412060,0.140704,0.333333,0.808943,-0.033231,0.881910
64,(kurma),(pir),0.412060,0.376884,0.125628,0.304878,0.808943,-0.029671,0.896412
65,(pir),(kurma),0.376884,0.412060,0.125628,0.333333,0.808943,-0.029671,0.881910
66,(pisang),(kurma),0.417085,0.412060,0.130653,0.313253,0.760212,-0.041211,0.856123
67,(kurma),(pisang),0.412060,0.417085,0.130653,0.317073,0.760212,-0.041211,0.853553
68,(kurma),(sawo),0.412060,0.447236,0.155779,0.378049,0.845300,-0.028509,0.888758
69,(sawo),(kurma),0.447236,0.412060,0.155779,0.348315,0.845300,-0.028509,0.902183
70,(mangga),(naga merah),0.391960,0.422111,0.130653,0.333333,0.789683,-0.034797,0.866834
71,(naga merah),(mangga),0.422111,0.391960,0.130653,0.309524,0.789683,-0.034797,0.880610
72,(mangga),(pir),0.391960,0.376884,0.130653,0.333333,0.884444,-0.017070,0.934673
73,(pir),(mangga),0.376884,0.391960,0.130653,0.346667,0.884444,-0.017070,0.930674
74,(pisang),(mangga),0.417085,0.391960,0.155779,0.373494,0.952888,-0.007702,0.970526
75,(mangga),(pisang),0.391960,0.417085,0.155779,0.397436,0.952888,-0.007702,0.967390
76,(mangga),(sawo),0.391960,0.447236,0.160804,0.410256,0.917315,-0.014495,0.937295
77,(sawo),(mangga),0.447236,0.391960,0.160804,0.359551,0.917315,-0.014495,0.949396
78,(pir),(naga merah),0.376884,0.422111,0.125628,0.333333,0.789683,-0.033459,0.866834
79,(naga merah),(pir),0.422111,0.376884,0.125628,0.297619,0.789683,-0.033459,0.887148
80,(pisang),(naga merah),0.417085,0.422111,0.175879,0.421687,0.998996,-0.000177,0.999267
81,(naga merah),(pisang),0.422111,0.417085,0.175879,0.416667,0.998996,-0.000177,0.999282
82,(naga merah),(sawo),0.422111,0.447236,0.160804,0.380952,0.851792,-0.027979,0.892926
83,(sawo),(naga merah),0.447236,0.422111,0.160804,0.359551,0.851792,-0.027979,0.902319
84,(pir),(sawo),0.376884,0.447236,0.155779,0.413333,0.924195,-0.012777,0.942211
85,(sawo),(pir),0.447236,0.376884,0.155779,0.348315,0.924195,-0.012777,0.956160
86,(pisang),(sawo),0.417085,0.447236,0.180905,0.433735,0.969812,-0.005631,0.976157
87,(sawo),(pisang),0.447236,0.417085,0.180905,0.404494,0.969812,-0.005631,0.978857

In [51]:
rules.shape

(4, 9)

In [52]:
rules[ (rules['lift'] >= 1) &
       (rules['confidence'] >= 0.4) ]

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,leverage,conviction
0,(pisang),(Anggur),0.417085,0.422111,0.190955,0.457831,1.084624,0.014899,1.065885
1,(Anggur),(pisang),0.422111,0.417085,0.190955,0.452381,1.084624,0.014899,1.064453
2,(Jeruk),(kurma),0.396985,0.412060,0.165829,0.417722,1.013739,0.002247,1.009723
3,(kurma),(Jeruk),0.412060,0.396985,0.165829,0.402439,1.013739,0.002247,1.009127

In [54]:
rules.to_csv('rule.csv', index=False)